"""add is_demo to users

Revision ID: 0ed66875b9a3
Revises: 97d8c9fcde35
Create Date: 2026-05-15 20:47:54.472755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed66875b9a3'
down_revision: Union[str, Sequence[str], None] = '97d8c9fcde35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_demo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_demo')
    # ### end Alembic commands ###
