"""add unique constraint to flashcard_reviews

Revision ID: 42e1362b8fcc
Revises: 748af495507b
Create Date: 2026-05-04 23:30:19.102233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e1362b8fcc'
down_revision: Union[str, Sequence[str], None] = '748af495507b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_material_card', 'flashcard_reviews', ['material_id', 'card_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_material_card', 'flashcard_reviews', type_='unique')
    # ### end Alembic commands ###
