"""add status and make nullable for StudyMaterial

Revision ID: 7026903629d7
Revises: 0ed66875b9a3
Create Date: 2026-05-16 13:48:00.259806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7026903629d7'
down_revision: Union[str, Sequence[str], None] = '0ed66875b9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_materials', sa.Column('status', sa.String(length=20), nullable=True))
    op.execute("UPDATE study_materials SET status = 'completed'")
    op.alter_column('study_materials', 'status', nullable=False)
    op.alter_column('study_materials', 'flashcards',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('study_materials', 'summary',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_materials', 'summary',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('study_materials', 'flashcards',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('study_materials', 'status')
    # ### end Alembic commands ###
