"""add_users_and_user_id_to_sessions

Revision ID: 97d8c9fcde35
Revises: 42e1362b8fcc
Create Date: 2026-05-06 01:23:47.744347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d8c9fcde35'
down_revision: Union[str, Sequence[str], None] = '42e1362b8fcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('study_sessions', sa.Column('user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'study_sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_sessions', type_='foreignkey')
    op.drop_column('study_sessions', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
